#!/usr/bin/env bash
# session-end.sh - SessionEnd hook for Agent-Foundry
#
# Reads the current session transcript from stdin (Claude Code / Hermes / Codex convention)
# and produces a structured session-distill artifact at:
#   plans/sessions/YYYY-MM-DD-<short-name>.md
#
# Wiring instructions per harness:
#
# Claude Code (settings.json):
#   "hooks": {
#     "SessionEnd": [{
#       "matcher": "*",
#       "hooks": [{
#         "type": "command",
#         "command": "bash ~/.claude/skills/agent-foundry/hooks/session-end.sh"
#       }]
#     }]
#   }
#
# Hermes (config.yaml):
#   hooks:
#     session_end:
#       command: bash ~/.claude/skills/agent-foundry/hooks/session-end.sh
#
# Codex (settings.json):
#   "hooks": {
#     "session_end": [{
#       "hooks": [{
#         "type": "command",
#         "command": "bash ~/.claude/skills/agent-foundry/hooks/session-end.sh"
#       }]
#     }]
#   }
#
# Usage:
#   bash session-end.sh                    # reads transcript from stdin (hook mode)
#   bash session-end.sh --transcript PATH  # reads from explicit file (manual mode)
#   bash session-end.sh --date YYYY-MM-DD  # override date (for re-runs)
#
# Exit codes:
#   0 - success (distill artifact written or no-op)
#   1 - missing prerequisites (no agent-foundry install, no transcripts dir)

set -e

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SESSIONS_DIR="$REPO_ROOT/plans/sessions"
TRANSCRIPT=""
DATE_OVERRIDE=""

# Parse args
while [[ $# -gt 0 ]]; do
  case "$1" in
    --transcript=*) TRANSCRIPT="${1#*=}" ;;
    --transcript)    TRANSCRIPT="$2"; shift ;;
    --date=*)        DATE_OVERRIDE="${1#*=}" ;;
    --date)          DATE_OVERRIDE="$2"; shift ;;
    --help|-h)
      grep "^#" "$0" | sed 's/^# \?//'
      exit 0
      ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
  shift
done

# Ensure sessions directory exists
mkdir -p "$SESSIONS_DIR"

# 1. Get the transcript
if [[ -n "$TRANSCRIPT" && -f "$TRANSCRIPT" ]]; then
  TRANSCRIPT_CONTENT=$(cat "$TRANSCRIPT")
elif [[ ! -t 0 ]]; then
  TRANSCRIPT_CONTENT=$(cat)
else
  echo "session-end: no transcript provided via stdin or --transcript, nothing to do" >&2
  exit 0
fi

# Skip if transcript is empty or trivial
if [[ -z "$TRANSCRIPT_CONTENT" || ${#TRANSCRIPT_CONTENT} -lt 100 ]]; then
  echo "session-end: transcript too short (${#TRANSCRIPT_CONTENT} chars), skipping" >&2
  exit 0
fi

# 2. Determine the date
DATE="${DATE_OVERRIDE:-$(date +%Y-%m-%d)}"

# 3. Generate a short name from the first non-empty user message
SHORT_NAME=$(echo "$TRANSCRIPT_CONTENT" | \
  grep -oE '"role":"user"' -A 1 | tail -1 | \
  grep -oE '"content":"[^"]*"' | head -1 | \
  sed 's/"content":"//; s/"$//; s/[^a-zA-Z0-9]/-/g; s/--*/-/g; s/^-//; s/-$//' | \
  cut -c1-40)
[[ -z "$SHORT_NAME" ]] && SHORT_NAME="session"

# 4. Build the artifact path (avoid collisions by appending -N)
OUT="$SESSIONS_DIR/${DATE}-${SHORT_NAME}.md"
N=1
while [[ -f "$OUT" ]]; do
  OUT="$SESSIONS_DIR/${DATE}-${SHORT_NAME}-${N}.md"
  N=$((N+1))
done

# 5. Generate the artifact
# Note: This template is filled in by the agent-foundry session-distill skill.
# When this hook runs, it should be invoked by a harness that has the
# session-distill skill loaded; otherwise, this script writes a placeholder
# that the user fills in by hand or by invoking the skill post-hoc.
cat > "$OUT" <<EOF
# Session: $DATE — $SHORT_NAME

> Auto-generated by Agent-Foundry session-end hook.
> Edit this file or invoke the \`session-distill\` skill to fill it in.

## What we did
<!-- One bullet per concrete change -->

## Decisions made
<!-- Format: **Decision**: ... because ... -->

## Files changed
<!-- One line per file -->

## Open questions
<!-- Punted questions; carry into next session -->

## Patterns observed
<!-- Reusable insights; feed into knowledge-extract -->

## Next session
<!-- Specific, not vague. With a file:line if applicable. -->

---

## Raw transcript (auto-attached)

\`\`\`
$TRANSCRIPT_CONTENT
\`\`\`
EOF

echo "session-end: wrote $OUT" >&2
exit 0
