"""Generate web/ assets from live repo state.

Works from any working directory: derives REPO from this script's location,
so the same script runs locally on Windows and on Linux (Vercel build workers).
"""
from __future__ import annotations

import base64
import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
WEB = REPO / "web"


def parse_frontmatter(text):
    m = re.match(r"^---\n(.*?)\n---\n?(.*)", text, re.DOTALL)
    if not m:
        return None, text
    fm = {}
    for line in m.group(1).split("\n"):
        if ":" in line and not line.startswith((" ", "-")):
            k, _, v = line.partition(":")
            fm[k.strip()] = v.strip().strip('"').strip("'")
    return fm, m.group(2)


# ── 1. site-data.js (with body_md) ──
skills = []
for sm in sorted((REPO / "skills").rglob("SKILL.md")):
    text = sm.read_text(encoding="utf-8")
    fm, body = parse_frontmatter(text)
    if not fm:
        continue
    rid = sm.parent.name
    rel = str(sm.relative_to(REPO)).replace("\\", "/")
    body_b64 = base64.b64encode(body.encode("utf-8")).decode("ascii")
    skills.append({
        "id": rid,
        "name": fm.get("name", rid),
        "description": fm.get("description", ""),
        "category": "core" if "/core/" in rel else "optional",
        "lines": text.count("\n"),
        "version": fm.get("version", "0.1.0"),
        "author": fm.get("author", "Agent Foundry Contributors"),
        "body_md": body_b64,
    })

agents = []
for ap in sorted((REPO / "agents").rglob("AGENT.md")):
    text = ap.read_text(encoding="utf-8")
    fm, body = parse_frontmatter(text)
    if not fm:
        continue
    body_b64 = base64.b64encode(body.encode("utf-8")).decode("ascii")
    agents.append({
        "id": ap.parent.name,
        "name": fm.get("name", ap.parent.name),
        "description": fm.get("description", ""),
        "model": fm.get("model", "inherit"),
        "body_md": body_b64,
    })

(WEB / "site-data.js").write_text(
    "// Auto-generated from skills/ SKILL.md and agents/ AGENT.md frontmatter.\n"
    "// DO NOT EDIT. Regenerate via scripts/gen-site-data.py.\n\n"
    f"const SKILLS = {json.dumps(skills, indent=2)};\n\n"
    f"const AGENTS = {json.dumps(agents, indent=2)};\n\n"
    f"const SKILL_COUNT = {len(skills)};\n"
    f"const AGENT_COUNT = {len(agents)};\n",
    encoding="utf-8",
)
print(f"site-data.js: {len(skills)} skills, {len(agents)} agents (with body_md)")

# ── 2. file-tree.js ──
def build_file_tree(base_path: Path, allowed_exts=(".py", ".md", ".html", ".css", ".js", ".toml", ".yaml", ".json", ".sh")):
    """Build a nested dict tree of source files, excluding common non-source dirs."""
    tree: dict = {}
    skip_dirs = {".git", "__pycache__", ".venv", "node_modules", "graphify-out", ".graphify-cache", "cache"}
    for f in sorted(base_path.rglob("*")):
        if not f.is_file() or f.suffix not in allowed_exts:
            continue
        rel = f.relative_to(base_path)
        parts = rel.parts
        if any(p in skip_dirs for p in parts):
            continue
        node = tree
        for p in parts[:-1]:
            node = node.setdefault(p, {"__files": {}})
            node = node["__files"]
        filename = parts[-1]
        node[filename] = {
            "path": str(rel).replace("\\", "/"),
            "size": f.stat().st_size,
            "ext": f.suffix,
        }
    return tree

tree = build_file_tree(REPO)
(WEB / "file-tree.js").write_text(
    "// File tree for the graph canvas file browser.\n"
    "// Generated by scripts/gen-site-data.py.\n\n"
    f"const FILE_TREE = {json.dumps(tree, indent=2)};\n",
    encoding="utf-8",
)
print(f"file-tree.js: file tree written")

# ── 2b. file-content.js (base64 source, for the in-app viewer) ──
def build_file_content(base_path: Path, allowed_exts=(".py", ".md", ".html", ".css", ".js", ".toml", ".yaml", ".yml", ".json", ".sh", ".txt"), max_bytes=120_000):
    """Embed source contents so file clicks render in-UI instead of redirecting to GitHub."""
    skip_dirs = {".git", "__pycache__", ".venv", "node_modules", "graphify-out", ".graphify-cache", "cache", "agent_foundry.egg-info", ".remember"}
    out: dict = {}
    for f in sorted(base_path.rglob("*")):
        if not f.is_file() or f.suffix not in allowed_exts:
            continue
        rel = f.relative_to(base_path)
        if any(p in skip_dirs for p in rel.parts):
            continue
        # skip the generated web data blobs (they are not interesting source)
        if rel.parts and rel.parts[0] == "web" and f.name.endswith("-data.js"):
            continue
        try:
            raw = f.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        if len(raw.encode("utf-8")) > max_bytes:
            raw = raw[:max_bytes] + "\n\n… (truncated — open on GitHub for the full file)"
        out[str(rel).replace("\\", "/")] = {
            "ext": f.suffix,
            "b64": base64.b64encode(raw.encode("utf-8")).decode("ascii"),
        }
    return out

file_content = build_file_content(REPO)
(WEB / "file-content.js").write_text(
    "// File contents for the in-app viewer (base64). Generated by scripts/gen-site-data.py.\n"
    "// DO NOT EDIT.\n\n"
    f"const FILE_CONTENT = {json.dumps(file_content, separators=(',', ':'))};\n",
    encoding="utf-8",
)
print(f"file-content.js: {len(file_content)} files embedded")


# ── 2c. diagrams: compile D2 sources → brand-themed SVG (fallback: keep committed) ──
import shutil
import subprocess

_D2_COLOR_MAP = {
    "1E1E2E": "131316", "313244": "1a1a1f", "45475A": "22222a", "585B70": "2a2a33",
    "6C7086": "8b8b95", "A6ADC8": "8b8b95", "BAC2DE": "c9c9d0", "CDD6F4": "e8e8ea",
    "CBA6F7": "f5a623", "F38BA8": "f5a623", "F5C2E7": "ff6b35", "89B4FA": "6496ff",
    "94E2D5": "4ade80", "A6E3A1": "4ade80",
}
_d2 = shutil.which("d2")
_dg = WEB / "diagrams"
if _d2 and _dg.exists():
    n = 0
    for src in sorted(_dg.glob("*.d2")):
        out = src.with_suffix(".svg")
        try:
            subprocess.run([_d2, "--theme", "200", "--pad", "8", str(src), str(out)], check=True, capture_output=True)
            svg = out.read_text(encoding="utf-8")
            for a, b in _D2_COLOR_MAP.items():
                svg = re.sub("#" + a, "#" + b, svg, flags=re.IGNORECASE)
            out.write_text(svg, encoding="utf-8")
            n += 1
        except Exception as exc:  # noqa: BLE001
            print(f"diagram: skipped {src.name} ({exc})")
    print(f"diagrams: recompiled {n} D2 source(s) via d2")
else:
    print("diagrams: d2 not on PATH — using committed SVGs")


# ── 3. graph-data.js + graph-stats.js ──
graph_path = REPO / "graphify-out" / "graph.json"
analysis_path = REPO / "graphify-out" / ".graphify_analysis.json"


def _preserve_committed_graph():
    if not (WEB / "graph-data.js").exists():
        (WEB / "graph-data.js").write_text(
            "// Stub (will be populated by graphify-run.py + gen-site-data.py)\n\n"
            "const GRAPH_NODES = [];\n\nconst GRAPH_EDGES = [];\n",
            encoding="utf-8",
        )
    if not (WEB / "graph-stats.js").exists():
        empty_stats = {
            "node_count": 0, "edge_count": 0,
            "skill_count": len(skills), "agent_count": len(agents),
            "community_count": 0, "god_nodes": [], "surprising": [],
        }
        (WEB / "graph-stats.js").write_text(
            "const GRAPH_STATS = " + json.dumps(empty_stats, indent=2) + ";\n",
            encoding="utf-8",
        )
    print("graph-data.js + graph-stats.js: preserved")


if graph_path.exists() and analysis_path.exists():
    graph = json.loads(graph_path.read_text(encoding="utf-8"))
    analysis = json.loads(analysis_path.read_text(encoding="utf-8"))

    # Precompute {stem: relpath} for source files ONCE (was an O(nodes × repo) rglob
    # per node — it walked .venv on every node and stalled the build).
    _skip = {".git", "__pycache__", ".venv", "node_modules", "graphify-out", ".graphify-cache", "cache", "agent_foundry.egg-info", ".remember"}
    py_by_stem: dict[str, str] = {}
    for candidate in sorted(REPO.rglob("*.py")):
        rel = candidate.relative_to(REPO)
        if any(p in _skip for p in rel.parts):
            continue
        py_by_stem.setdefault(candidate.stem, str(rel).replace("\\", "/"))

    # Map node IDs to file paths (extracted from the node label / id)
    nodes_js = []
    for n in graph.get("nodes", []):
        label = n.get("label", n.get("id", ""))
        nid = n["id"]
        # Infer file path from node id convention "module_file_function"
        parts = nid.split("_")
        file_path = py_by_stem.get(parts[1], "") if len(parts) >= 2 else ""
        nodes_js.append({
            "id": nid,
            "label": (label[:45] + "…") if len(label) > 45 else label,
            "title": n.get("title", label),
            "group": str(n.get("community", "0")),
            "file": file_path,
        })

    edges_js = []
    for e in graph.get("links", graph.get("edges", [])):
        edges_js.append({
            "from": e.get("source", ""),
            "to": e.get("target", ""),
            "label": e.get("relation", e.get("type", "")),
            "arrows": "to",
        })

    (WEB / "graph-data.js").write_text(
        "// Knowledge graph. Regenerate via graphify-run.py + gen-site-data.py.\n\n"
        f"const GRAPH_NODES = {json.dumps(nodes_js)};\n\n"
        f"const GRAPH_EDGES = {json.dumps(edges_js)};\n",
        encoding="utf-8",
    )
    print(f"graph-data.js: {len(nodes_js)} nodes, {len(edges_js)} edges")

    stats = {
        "node_count": len(nodes_js),
        "edge_count": len(edges_js),
        "skill_count": len(skills),
        "agent_count": len(agents),
        "community_count": len(analysis.get("communities", {})),
        "god_nodes": [
            {"label": g["label"], "degree": g["degree"]}
            for g in analysis.get("gods", [])[:10]
        ],
        "surprising": [
            {"source": s.get("source", ""), "target": s.get("target", ""), "relation": s.get("relation", "")}
            for s in analysis.get("surprises", [])[:10]
        ],
    }
    (WEB / "graph-stats.js").write_text(
        "const GRAPH_STATS = " + json.dumps(stats, indent=2) + ";\n",
        encoding="utf-8",
    )
    print(f"graph-stats.js: stats written")
else:
    _preserve_committed_graph()

# ── 4. install-data.js ──
install_data = {
    "core": "curl -fsSL https://raw.githubusercontent.com/youcisla/Agent-Foundry/main/install.sh | bash",
    "coreProfile": "AF_PROFILE=core curl -fsSL https://raw.githubusercontent.com/youcisla/Agent-Foundry/main/install.sh | bash",
    "fullProfile": "AF_PROFILE=full curl -fsSL https://raw.githubusercontent.com/youcisla/Agent-Foundry/main/install.sh | bash",
    "minimalProfile": "AF_PROFILE=minimal curl -fsSL https://raw.githubusercontent.com/youcisla/Agent-Foundry/main/install.sh | bash",
    "gitClone": "git clone https://github.com/youcisla/Agent-Foundry.git ~/.agent-foundry && cd ~/.agent-foundry && pip install -e .",
    "claudeCode": "/plugin marketplace add youcisla/Agent-Foundry\n/plugin install agent-foundry",
    "npm": "npm i -g agent-foundry",
}
(WEB / "install-data.js").write_text(
    "const INSTALL_COMMANDS = " + json.dumps(install_data, indent=2) + ";\n",
    encoding="utf-8",
)
print("install-data.js: written")

# ── 5. skill-deps.js ──
deps_map = {}
all_skill_ids = set()
for sm in (REPO / "skills").rglob("SKILL.md"):
    all_skill_ids.add(sm.parent.name)
for sm in sorted((REPO / "skills").rglob("SKILL.md")):
    text = sm.read_text(encoding="utf-8")
    body = text.split("---", 2)[-1] if text.count("---") >= 2 else text
    rid = sm.parent.name
    mentioned = sorted({
        sid for sid in all_skill_ids
        if sid != rid and (f"`{sid}`" in body or f"see {sid}" in body or f"({sid})" in body)
    })
    deps_map[rid] = mentioned
(WEB / "skill-deps.js").write_text(
    "// Skill dependency map.\n"
    f"const SKILL_DEPS = {json.dumps(deps_map, indent=2)};\n",
    encoding="utf-8",
)
total_with_deps = sum(1 for v in deps_map.values() if v)
print(f"skill-deps.js: {total_with_deps}/{len(all_skill_ids)} skills have cross-references")

# ── 6. adapters-data.js — preserve if exists ──
if not (WEB / "adapters-data.js").exists():
    (WEB / "adapters-data.js").write_text("const ADAPTERS = [];\n", encoding="utf-8")
print("adapters-data.js: preserved")

# ── 7. data.json — single source polled by the reactive store (store.js) ──
import time

_gstats = {}
_gs = WEB / "graph-stats.js"
if _gs.exists():
    _txt = _gs.read_text(encoding="utf-8")
    _i, _j = _txt.find("{"), _txt.rfind("}")
    if _i != -1 and _j != -1:
        try:
            _gstats = json.loads(_txt[_i:_j + 1])
        except json.JSONDecodeError:
            _gstats = {}
data_json = {
    "skills": skills,
    "agents": agents,
    "skill_count": len(skills),
    "agent_count": len(agents),
    "graph_stats": _gstats,
    "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
}
(WEB / "data.json").write_text(json.dumps(data_json, separators=(",", ":")), encoding="utf-8")
print("data.json: written (reactive store source)")

print("done.")
