#!/usr/bin/env bash
# skill-update.sh - Weekly scan for upstream skill updates
#
# Reads catalog/skills.csv, fetches the latest commit hash from each
# non-skipped upstream source, compares against catalog/state.json,
# and writes a digest of changes to plans/updates/YYYY-MM-DD.md
#
# Usage:
#   ./scripts/skill-update.sh                # full scan
#   ./scripts/skill-update.sh --dry-run      # show what would be done, no writes
#   ./scripts/skill-update.sh --source URL   # scan a single source
#
# Designed to be run from:
#   - Weekly cron on the host (Sunday 9am)
#   - GitHub Actions workflow (see workflows/skill-update.md)
#   - Manual invocation in any agent session

set -e

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CSV="$REPO_ROOT/catalog/skills.csv"
STATE="$REPO_ROOT/catalog/state.json"
UPDATES_DIR="$REPO_ROOT/plans/updates"
DATE="$(date +%Y-%m-%d)"

DRY_RUN=false
SINGLE_SOURCE=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run)    DRY_RUN=true ;;
    --source=*)    SINGLE_SOURCE="${1#*=}" ;;
    --source)      SINGLE_SOURCE="$2"; shift ;;
    --help|-h)
      grep "^#" "$0" | sed 's/^# \?//'
      exit 0
      ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
  shift
done

[[ ! -f "$CSV" ]] && { echo "catalog/skills.csv not found" >&2; exit 1; }

# 1. Initialize state.json if missing
if [[ ! -f "$STATE" ]]; then
  [[ "$DRY_RUN" == "false" ]] && mkdir -p "$(dirname "$STATE")"
  echo '{"sources": {}}' > "$STATE"
  echo "skill-update: created $STATE" >&2
fi

# 2. Read the catalog (CSV: url,name,category,license,verdict,priority,notes,status)
# Skip header, skip skip rows, dedupe by url
SOURCES=$(awk -F',' 'NR>1 && $5!="skip" {print $1}' "$CSV" | sort -u)

# 3. For each source, fetch latest commit hash from GitHub API
DIGEST="$UPDATES_DIR/${DATE}-upstream-scan.md"
[[ "$DRY_RUN" == "false" ]] && mkdir -p "$UPDATES_DIR"

if [[ "$DRY_RUN" == "false" ]]; then
  cat > "$DIGEST" <<EOF
# Upstream Skill Scan — $DATE

> Auto-generated by scripts/skill-update.sh.
> Review changes and decide which to port.

EOF
fi

CHANGES=0
SCANNED=0
FAILED=0

echo "Scanning upstream sources..."
echo "$SOURCES" | while read -r url; do
  [[ -z "$url" ]] && continue
  [[ -n "$SINGLE_SOURCE" && "$url" != "$SINGLE_SOURCE" ]] && continue

  # Extract owner/repo from github.com URL
  owner_repo=$(echo "$url" | sed -n 's|.*github.com/\([^/]*/[^/]*\).*|\1|p' | sed 's|\.git$||')
  [[ -z "$owner_repo" ]] && { echo "  skip (not github): $url"; continue; }

  SCANNED=$((SCANNED + 1))

  # Fetch latest commit (with timeout, no fail on network)
  latest=$(curl -fsS --max-time 10 "https://api.github.com/repos/$owner_repo/commits?per_page=1" 2>/dev/null | \
    grep -oE '"sha":"[a-f0-9]{7,40}"' | head -1 | sed 's/"sha":"//; s/"$//')

  if [[ -z "$latest" ]]; then
    FAILED=$((FAILED + 1))
    echo "  fail (network): $owner_repo"
    continue
  fi

  # Known hash from state.json
  known=$(jq -r --arg k "$url" '.sources[$k] // "unknown"' "$STATE" 2>/dev/null)

  if [[ "$latest" != "$known" ]]; then
    CHANGES=$((CHANGES + 1))
    echo "  changed: $owner_repo ($known → $latest)"
    [[ "$DRY_RUN" == "false" ]] && \
      echo "- 🔄 **$owner_repo** (\`$url\`): \`$known\` → \`$latest\`" >> "$DIGEST"
  else
    echo "  unchanged: $owner_repo"
  fi
done

# Stats summary
TOTAL=$(echo "$SOURCES" | wc -l)
echo ""
echo "=== Summary ==="
echo "Total sources: $TOTAL"
echo "Scanned: $SCANNED"
echo "Failed (network): $FAILED"
echo "Changed: $CHANGES"

if [[ "$DRY_RUN" == "true" ]]; then
  echo ""
  echo "(dry-run mode — no files written)"
  exit 0
fi

# 4. Append summary to digest
cat >> "$DIGEST" <<EOF

---

## Summary

- Total sources: $TOTAL
- Scanned: $SCANNED
- Failed (network or API): $FAILED
- Changed since last scan: $CHANGES

## Next steps

For each change:
1. Visit the source repo, review the diff
2. Decide: port the change, or skip with reason
3. Update \`catalog/state.json\` to record the new hash
4. If the change is material, open a PR

EOF

echo ""
echo "Digest written: $DIGEST"
echo ""
if [[ "$CHANGES" -gt 0 ]]; then
  echo "Review with: cat $DIGEST"
fi

exit 0
