"""Config management: ~/.config/agent-foundry/config.toml."""
from __future__ import annotations

import os
import sys
import tomllib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


CONFIG_PATH = Path.home() / ".config" / "agent-foundry" / "config.toml"
LOG_DB_PATH = Path.home() / ".config" / "agent-foundry" / "executions.db"
INDEX_CACHE_TTL_DEFAULT = 60  # seconds

DEFAULT_CONFIG = """# Agent Foundry configuration
# Edit this file to tune the orchestrator.

[core]
skills_dir = "~/.claude/plugins/agent-foundry/skills"
index_path = "~/.config/agent-foundry/skills-index.json"
default_llm = "claude-3-7-sonnet-20250219"
token_budget = 100000
daemon_port = 8765
index_cache_ttl_seconds = 60
harness_type = "claude-code"

[planner]
# Score added per matched trigger pattern (regex).
pattern_match_weight = 0.3
# Score added if skill name or description appears in the prompt.
name_in_prompt_boost = 0.2
# Larger value = weaker cost penalty in the ranker.
cost_penalty_divisor = 5000.0
# Default top-N returned by /plan.
max_results = 5

# System prompt for the generic-reasoning fallback skill.
# Edit to override the built-in default.
# fallback_system_prompt = "You are a helpful assistant..."
"""


@dataclass
class PlannerConfig:
    pattern_match_weight: float = 0.3
    name_in_prompt_boost: float = 0.2
    cost_penalty_divisor: float = 5000.0
    max_results: int = 5


@dataclass
class CoreConfig:
    skills_dir: str = "~/.claude/plugins/agent-foundry/skills"
    index_path: str = "~/.config/agent-foundry/skills-index.json"
    default_llm: str = "claude-3-7-sonnet-20250219"
    token_budget: int = 100000
    daemon_port: int = 8765
    index_cache_ttl_seconds: int = 60
    harness_type: str = "claude-code"


@dataclass
class Config:
    core: CoreConfig = field(default_factory=CoreConfig)
    planner: PlannerConfig = field(default_factory=PlannerConfig)
    fallback_system_prompt: str | None = None
    config_path: Path = CONFIG_PATH

    @classmethod
    def load(cls, path: Path | None = None) -> "Config":
        """Load config from path (default: ~/.config/agent-foundry/config.toml).
        Missing file or sections fall back to defaults."""
        p = Path(path) if path else CONFIG_PATH
        cfg = cls()
        cfg.config_path = p
        if not p.exists():
            return cfg

        try:
            with open(p, "rb") as f:
                data = tomllib.load(f)
        except Exception as exc:
            print(f"WARN: failed to parse {p}: {exc}", file=sys.stderr)
            return cfg

        core = data.get("core", {})
        for k in cfg.core.__dataclass_fields__:
            if k in core:
                setattr(cfg.core, k, core[k])

        planner = data.get("planner", {})
        for k in cfg.planner.__dataclass_fields__:
            if k in planner:
                setattr(cfg.planner, k, planner[k])

        cfg.fallback_system_prompt = data.get("fallback_system_prompt")
        return cfg

    def save(self, path: Path | None = None) -> Path:
        """Write current config to disk (overwrites)."""
        p = Path(path) if path else self.config_path
        p.parent.mkdir(parents=True, exist_ok=True)

        # Render manually (preserves section comments)
        lines: list[str] = []
        lines.append("# Agent Foundry configuration")
        lines.append("# Generated by `agent-foundry init`. Edit to tune.")
        lines.append("")
        lines.append("[core]")
        for k, v in vars(self.core).items():
            v_str = f'"{v}"' if isinstance(v, str) else str(v)
            lines.append(f"{k} = {v_str}")
        lines.append("")
        lines.append("[planner]")
        for k, v in vars(self.planner).items():
            v_str = f'"{v}"' if isinstance(v, str) else str(v)
            lines.append(f"{k} = {v_str}")
        lines.append("")
        if self.fallback_system_prompt is not None:
            # toml multiline
            lines.append("# Optional override for the generic-reasoning fallback prompt.")
            escaped = self.fallback_system_prompt.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'fallback_system_prompt = "{escaped}"')
            lines.append("")
        else:
            lines.append("# Uncomment to override the fallback prompt:")
            lines.append('# fallback_system_prompt = "You are a helpful assistant..."')
            lines.append("")

        p.write_text("\n".join(lines))
        return p


def init_config(force: bool = False) -> Config:
    """Create config dir + default config file. Returns loaded config."""
    CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    if not CONFIG_PATH.exists() or force:
        cfg = Config()
        cfg.save()
    return Config.load()
