#!/usr/bin/env python3
"""autonomous_briefing.py - orchestrate the daily briefing."""

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path

DEFAULT_MEM = "~/.agent-memory"


def read_memory(memory_home, topic, key=None):
    mem_script = Path(memory_home).expanduser() / "scripts" / "memory.py"
    # Use the agent-memory-vault script if available
    candidates = [
        Path(os.environ.get("HERMES_SKILLS_ROOT", str(Path.home() / "AppData/Local/hermes/skills"))) / "agentic" / "agent-memory-vault" / "scripts" / "memory.py",
    ]
    for c in candidates:
        if c.exists():
            mem_script = c
            break
    if key:
        cmd = ["python", str(mem_script), "get", "--topic", topic, "--key", key]
        r = subprocess.run(cmd, capture_output=True, text=True)
        if r.returncode == 0:
            try:
                return json.loads(r.stdout)
            except Exception:
                return None
    return None


def write_memory(memory_home, topic, key, value):
    candidates = [
        Path(os.environ.get("HERMES_SKILLS_ROOT", str(Path.home() / "AppData/Local/hermes/skills"))) / "agentic" / "agent-memory-vault" / "scripts" / "memory.py",
    ]
    mem_script = None
    for c in candidates:
        if c.exists():
            mem_script = c
            break
    if mem_script is None:
        print("[briefing] WARNING: memory-vault script not found")
        return False
    r = subprocess.run(
        ["python", str(mem_script), "put", "--topic", topic, "--key", key, "--value", value],
        capture_output=True, text=True
    )
    return r.returncode == 0


def run_last30days(topic, sources="reddit,hackernews", days=1):
    """Run last30days and return parsed JSON."""
    candidates = [
        Path(os.environ.get("HERMES_SKILLS_ROOT", str(Path.home() / "AppData/Local/hermes/skills"))) / "research" / "last30days" / "scripts" / "last30days.py",
        Path.home() / "AppData/Local/hermes/skills/research/last30days/scripts/last30days.py",
    ]
    script = None
    for c in candidates:
        if c.exists():
            script = c
            break
    if script is None:
        return None
    env = os.environ.copy()
    cmd = [str(Path.home() / ".local/bin/python3.12.exe") if (Path.home() / ".local/bin/python3.12.exe").exists() else "python3.12", str(script), topic, "--search", sources, "--days", str(days), "--emit", "json", "--quick"]
    r = subprocess.run(cmd, capture_output=True, text=True, env=env, timeout=180)
    if r.returncode != 0:
        print("[briefing] last30days failed: " + r.stderr[:300])
        return None
    try:
        return json.loads(r.stdout)
    except Exception:
        return None


def run_hf_trending(limit=10):
    candidates = [
        Path(os.environ.get("HERMES_SKILLS_ROOT", str(Path.home() / "AppData/Local/hermes/skills"))) / "huggingface-dataset-intel" / "scripts" / "hf-top-datasets.py",
    ]
    for c in candidates:
        if c.exists():
            r = subprocess.run(["python", str(c), "--limit", str(limit)], capture_output=True, text=True, timeout=60)
            return r.stdout if r.returncode == 0 else None
    return None


def render_briefing(date_str, last30days_out, hf_out, memory_delta, actions):
    lines = []
    lines.append("# Autonomous Briefing - " + date_str)
    lines.append("")
    lines.append("Generated by `autonomous-briefing` skill.")
    lines.append("")
    lines.append("## 1. Trending research (last30days)")
    lines.append("")
    if last30days_out:
        clusters = last30days_out.get("clusters", [])[:5]
        for c in clusters:
            title = c.get("title", "?")[:90]
            src = ",".join(c.get("sources", []))
            lines.append("- **[" + src + "]** " + title)
    else:
        lines.append("- (last30days not available or no results)")
    lines.append("")
    lines.append("## 2. ML/AI ecosystem (HuggingFace)")
    lines.append("")
    if hf_out:
        for line in hf_out.split("\n")[:15]:
            if line.strip():
                lines.append("- " + line)
    else:
        lines.append("- (HF trending monitor not available)")
    lines.append("")
    lines.append("## 3. Memory delta")
    lines.append("")
    if memory_delta:
        for k, v in memory_delta.items():
            lines.append("- **" + k + "**: " + str(v))
    else:
        lines.append("- (no previous briefing to compare)")
    lines.append("")
    lines.append("## 4. Today's top 3 actions")
    lines.append("")
    for a in actions[:3]:
        lines.append("- " + a)
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("Run by autonomous-briefing skill v1.0. Compliant with effective-agent-skills format.")
    return "\n".join(lines)


def main():
    p = argparse.ArgumentParser(description="Autonomous daily briefing")
    p.add_argument("--memory-home", default=DEFAULT_MEM)
    p.add_argument("--sources", default="reddit,hackernews")
    p.add_argument("--days", type=int, default=1)
    p.add_argument("--topic", default="AI news")
    p.add_argument("--output", help="Write to file")
    p.add_argument("--emit", default="md")
    p.add_argument("--save-to-memory", action="store_true", default=True)
    args = p.parse_args()

    today = datetime.now().strftime("%Y-%m-%d")
    print("[briefing] Date: " + today)
    print("[briefing] Topic: " + args.topic)

    print("[briefing] Step 1: last30days...")
    l30 = run_last30days(args.topic, sources=args.sources, days=args.days)

    print("[briefing] Step 2: HF trending...")
    hf = run_hf_trending(limit=10)

    print("[briefing] Step 3: memory delta (placeholder)...")
    prev = read_memory(args.memory_home, "briefing", key=(today + " delta"))
    memory_delta = {"previous_briefing": "loaded" if prev else "none"}

    actions = [
        "Review top 1 trending cluster from last30days",
        "Check new HF datasets in your tracked categories",
        "Run goal-loop on the highest-priority action",
    ]

    output = render_briefing(today, l30, hf, memory_delta, actions)

    if args.output:
        Path(args.output).parent.mkdir(parents=True, exist_ok=True)
        Path(args.output).write_text(output, encoding="utf-8")
        print("[briefing] Wrote: " + args.output)
    else:
        print(output)

    if args.save_to_memory:
        write_memory(args.memory_home, "briefing", today, output[:500])
        write_memory(args.memory_home, "briefing-dates", today, "generated")
        print("[briefing] Saved to memory-vault")


if __name__ == "__main__":
    main()
