// Auto-regenerated by gen-site-data.py if missing. Hand-curated.
// Status: 'tested' / 'beta' / 'coming-soon'
const ADAPTERS = [
  { id: 'claude-code',   name: 'Claude Code',         status: 'tested',      path: '~/.claude/skills/agent-foundry',                    note: 'Smoke-tested on this machine. 31 skills discoverable via symlink.' },
  { id: 'codex',         name: 'Codex CLI',           status: 'tested',      path: '~/.codex/skills/agent-foundry',                     note: 'Smoke-tested. AGENTS.md + config.toml + 2 agent role TOMLs all load.' },
  { id: 'hermes',        name: 'Hermes',              status: 'tested',      path: '~/AppData/Local/hermes/skills/agent-foundry',       note: 'Smoke-tested. Skills discoverable via symlink.' },
  { id: 'cursor',        name: 'Cursor',              status: 'beta',        path: '~/.cursor/rules/agent-foundry-*.mdc',                note: 'Adapter structure defined. hooks.json + 2 .mdc rules ship in repo.' },
  { id: 'opencode',      name: 'OpenCode',            status: 'beta',        path: '~/.config/opencode/agent-foundry-config/',           note: 'opencode.json + instructions/ ship in repo.' },
  { id: 'gemini-cli',    name: 'Gemini CLI',          status: 'beta',        path: '~/.gemini/agent-foundry-config/AGENTS.md',           note: 'AGENTS.md reference doc. No plugin API yet.' },
  { id: 'antigravity',   name: 'Antigravity',         status: 'beta',        path: '~/.agent/{rules,skills,workflows}/',                 note: 'Rules + skills + workflows layout in repo.' },
  { id: 'codebuddy',     name: 'Codebuddy',           status: 'beta',        path: '~/.codebuddy/{skills,commands}/',                    note: 'Skills + commands layout in repo.' },
  { id: 'joycode',       name: 'JoyCode',             status: 'beta',        path: '~/.joycode/{skills,commands}/',                      note: 'Skills + commands layout in repo.' },
  { id: 'qwen',          name: 'Qwen CLI',            status: 'beta',        path: '~/.qwen/skills/agent-foundry/',                      note: 'Skills layout in repo.' },
  { id: 'kimi',          name: 'Kimi',                status: 'beta',        path: '~/.kimi/skills/agent-foundry/',                      note: 'Skills layout in repo. Community-reported API.' },
  { id: 'openclaw',      name: 'OpenClaw',            status: 'beta',        path: '~/.openclaw/skills/agent-foundry/',                   note: 'Skills layout in repo.' },
  { id: 'claude-project',name: 'Claude Code (local)', status: 'coming-soon', path: './.claude/skills/agent-foundry',                     note: 'Per-project install path. Aliases claude-code today.' },
  { id: 'zed',           name: 'Zed (zquire)',        status: 'coming-soon', path: '~/.zed/{commands,agents}/',                           note: "Zed's zquire is in beta with unstable plugin API." },
];