// Harness adapter status — what we ship, what we test.
// Auto-generated by docs/adapters/README.md. Keep in sync manually.

const ADAPTERS = [
  {
    id: "claude-code",
    name: "Claude Code",
    path: "~/.claude/skills/agent-foundry",
    status: "tested",
    note: "Install verified 2026-07-20. 31 skills discoverable."
  },
  {
    id: "hermes",
    name: "Hermes",
    path: "~/AppData/Local/hermes/skills/agent-foundry",
    status: "tested",
    note: "Install verified 2026-07-20. Same indexer result as Claude Code."
  },
  {
    id: "codex",
    name: "Codex CLI",
    path: "~/.codex/skills/agent-foundry",
    status: "tested",
    note: "codex-cli 0.144.6, npm install. AGENTS.md + 31 skills + 2 agent roles all load. Auth-blocked (no API key)."
  },
  {
    id: "cursor",
    name: "Cursor",
    path: ".cursor/rules/agent-foundry.mdc",
    status: "documented",
    note: "Hooks + 2 rules installed via --harness=cursor. No Cursor binary to test."
  },
  {
    id: "gemini-cli",
    name: "Gemini CLI",
    path: "~/.gemini/skills/agent-foundry",
    status: "untested",
    note: "Config AGENTS.md shipped. Gemini CLI has no plugin system."
  },
  {
    id: "opencode",
    name: "OpenCode",
    path: "~/.config/opencode/skills/agent-foundry",
    status: "documented",
    note: "Skills + opensechat.json + agents shipped. Config merge via jq."
  },
];