// File tree for the graph canvas file browser.
// Generated by scripts/gen-site-data.py.

const FILE_TREE = {
  ".claude-plugin": {
    "__files": {
      "marketplace.json": {
        "path": ".claude-plugin/marketplace.json",
        "size": 292,
        "ext": ".json"
      },
      "plugin.json": {
        "path": ".claude-plugin/plugin.json",
        "size": 461,
        "ext": ".json"
      }
    }
  },
  ".codex": {
    "__files": {
      "AGENTS.md": {
        "path": ".codex/AGENTS.md",
        "size": 4195,
        "ext": ".md"
      },
      "config.toml": {
        "path": ".codex/config.toml",
        "size": 1931,
        "ext": ".toml"
      }
    }
  },
  ".cursor": {
    "__files": {
      "hooks.json": {
        "path": ".cursor/hooks.json",
        "size": 278,
        "ext": ".json"
      }
    }
  },
  ".cursor-rules.md": {
    "path": ".cursor-rules.md",
    "size": 477,
    "ext": ".md"
  },
  ".gemini": {
    "__files": {
      "AGENTS.md": {
        "path": ".gemini/AGENTS.md",
        "size": 399,
        "ext": ".md"
      }
    }
  },
  ".opencode": {
    "__files": {
      "instructions": {
        "__files": {
          "PLAN.md": {
            "path": ".opencode/instructions/PLAN.md",
            "size": 227,
            "ext": ".md"
          },
          "VERIFY.md": {
            "path": ".opencode/instructions/VERIFY.md",
            "size": 264,
            "ext": ".md"
          }
        }
      },
      "opencode.json": {
        "path": ".opencode/opencode.json",
        "size": 2446,
        "ext": ".json"
      }
    }
  },
  "agent_foundry": {
    "__files": {
      "__init__.py": {
        "path": "agent_foundry/__init__.py",
        "size": 82,
        "ext": ".py"
      },
      "__main__.py": {
        "path": "agent_foundry/__main__.py",
        "size": 101,
        "ext": ".py"
      },
      "cli.py": {
        "path": "agent_foundry/cli.py",
        "size": 17316,
        "ext": ".py"
      },
      "config.py": {
        "path": "agent_foundry/config.py",
        "size": 6429,
        "ext": ".py"
      },
      "daemon.py": {
        "path": "agent_foundry/daemon.py",
        "size": 4017,
        "ext": ".py"
      },
      "executor.py": {
        "path": "agent_foundry/executor.py",
        "size": 4162,
        "ext": ".py"
      },
      "indexer.py": {
        "path": "agent_foundry/indexer.py",
        "size": 8828,
        "ext": ".py"
      },
      "judge.py": {
        "path": "agent_foundry/judge.py",
        "size": 2529,
        "ext": ".py"
      },
      "logging_db.py": {
        "path": "agent_foundry/logging_db.py",
        "size": 9444,
        "ext": ".py"
      },
      "loop.py": {
        "path": "agent_foundry/loop.py",
        "size": 6435,
        "ext": ".py"
      },
      "models.py": {
        "path": "agent_foundry/models.py",
        "size": 4198,
        "ext": ".py"
      },
      "planner.py": {
        "path": "agent_foundry/planner.py",
        "size": 4221,
        "ext": ".py"
      }
    }
  },
  "agents": {
    "__files": {
      "af-critic": {
        "__files": {
          "AGENT.md": {
            "path": "agents/af-critic/AGENT.md",
            "size": 2561,
            "ext": ".md"
          },
          "agents": {
            "__files": {
              "openai.toml": {
                "path": "agents/af-critic/agents/openai.toml",
                "size": 552,
                "ext": ".toml"
              }
            }
          }
        }
      },
      "af-orchestrator": {
        "__files": {
          "AGENT.md": {
            "path": "agents/af-orchestrator/AGENT.md",
            "size": 1328,
            "ext": ".md"
          }
        }
      },
      "af-planner": {
        "__files": {
          "AGENT.md": {
            "path": "agents/af-planner/AGENT.md",
            "size": 2416,
            "ext": ".md"
          },
          "agents": {
            "__files": {
              "openai.toml": {
                "path": "agents/af-planner/agents/openai.toml",
                "size": 695,
                "ext": ".toml"
              }
            }
          }
        }
      }
    }
  },
  "AUTHORSHIP.md": {
    "path": "AUTHORSHIP.md",
    "size": 644,
    "ext": ".md"
  },
  "catalog": {
    "__files": {
      "decisions.md": {
        "path": "catalog/decisions.md",
        "size": 3851,
        "ext": ".md"
      }
    }
  },
  "CHANGELOG.md": {
    "path": "CHANGELOG.md",
    "size": 4475,
    "ext": ".md"
  },
  "claude_code_plugin.json": {
    "path": "claude_code_plugin.json",
    "size": 546,
    "ext": ".json"
  },
  "community": {
    "__files": {
      "README.md": {
        "path": "community/README.md",
        "size": 571,
        "ext": ".md"
      }
    }
  },
  "docs": {
    "__files": {
      "adapters": {
        "__files": {
          "gemini-cli.md": {
            "path": "docs/adapters/gemini-cli.md",
            "size": 734,
            "ext": ".md"
          },
          "opencode.md": {
            "path": "docs/adapters/opencode.md",
            "size": 82,
            "ext": ".md"
          },
          "README.md": {
            "path": "docs/adapters/README.md",
            "size": 3174,
            "ext": ".md"
          }
        }
      },
      "architecture": {
        "__files": {
          "community-cohesion.md": {
            "path": "docs/architecture/community-cohesion.md",
            "size": 4066,
            "ext": ".md"
          }
        }
      },
      "architecture.md": {
        "path": "docs/architecture.md",
        "size": 6698,
        "ext": ".md"
      },
      "authoring.md": {
        "path": "docs/authoring.md",
        "size": 6254,
        "ext": ".md"
      },
      "auto-learning.md": {
        "path": "docs/auto-learning.md",
        "size": 3558,
        "ext": ".md"
      },
      "launch-plan.md": {
        "path": "docs/launch-plan.md",
        "size": 27108,
        "ext": ".md"
      },
      "philosophy.md": {
        "path": "docs/philosophy.md",
        "size": 3313,
        "ext": ".md"
      }
    }
  },
  "hooks": {
    "__files": {
      "session-closeout.sh": {
        "path": "hooks/session-closeout.sh",
        "size": 442,
        "ext": ".sh"
      },
      "session-end.sh": {
        "path": "hooks/session-end.sh",
        "size": 4795,
        "ext": ".sh"
      }
    }
  },
  "INSTALL.md": {
    "path": "INSTALL.md",
    "size": 2444,
    "ext": ".md"
  },
  "install.sh": {
    "path": "install.sh",
    "size": 2681,
    "ext": ".sh"
  },
  "pyproject.toml": {
    "path": "pyproject.toml",
    "size": 804,
    "ext": ".toml"
  },
  "README.md": {
    "path": "README.md",
    "size": 13359,
    "ext": ".md"
  },
  "schemas": {
    "__files": {
      "skill-manifest.schema.json": {
        "path": "schemas/skill-manifest.schema.json",
        "size": 2766,
        "ext": ".json"
      }
    }
  },
  "scripts": {
    "__files": {
      "auto-extract.sh": {
        "path": "scripts/auto-extract.sh",
        "size": 3507,
        "ext": ".sh"
      },
      "build-site-data.sh": {
        "path": "scripts/build-site-data.sh",
        "size": 2152,
        "ext": ".sh"
      },
      "cost-report.py": {
        "path": "scripts/cost-report.py",
        "size": 3858,
        "ext": ".py"
      },
      "foundry-eval.py": {
        "path": "scripts/foundry-eval.py",
        "size": 9042,
        "ext": ".py"
      },
      "gen-site-data.py": {
        "path": "scripts/gen-site-data.py",
        "size": 9520,
        "ext": ".py"
      },
      "graphify-run.py": {
        "path": "scripts/graphify-run.py",
        "size": 6632,
        "ext": ".py"
      },
      "indexer.py": {
        "path": "scripts/indexer.py",
        "size": 10330,
        "ext": ".py"
      },
      "install.sh": {
        "path": "scripts/install.sh",
        "size": 6648,
        "ext": ".sh"
      },
      "nox.sh": {
        "path": "scripts/nox.sh",
        "size": 1818,
        "ext": ".sh"
      },
      "provenance-audit.py": {
        "path": "scripts/provenance-audit.py",
        "size": 6501,
        "ext": ".py"
      },
      "smoke-test.py": {
        "path": "scripts/smoke-test.py",
        "size": 4583,
        "ext": ".py"
      },
      "validate.sh": {
        "path": "scripts/validate.sh",
        "size": 2531,
        "ext": ".sh"
      }
    }
  },
  "skills": {
    "__files": {
      "core": {
        "__files": {
          "anti-slop": {
            "__files": {
              "SKILL.md": {
                "path": "skills/core/anti-slop/SKILL.md",
                "size": 2376,
                "ext": ".md"
              }
            }
          },
          "api-design": {
            "__files": {
              "references": {
                "__files": {
                  "details.md": {
                    "path": "skills/core/api-design/references/details.md",
                    "size": 1945,
                    "ext": ".md"
                  }
                }
              },
              "SKILL.md": {
                "path": "skills/core/api-design/SKILL.md",
                "size": 1827,
                "ext": ".md"
              }
            }
          },
          "automation-pick": {
            "__files": {
              "references": {
                "__files": {
                  "details.md": {
                    "path": "skills/core/automation-pick/references/details.md",
                    "size": 2576,
                    "ext": ".md"
                  }
                }
              },
              "SKILL.md": {
                "path": "skills/core/automation-pick/SKILL.md",
                "size": 2045,
                "ext": ".md"
              }
            }
          },
          "bottleneck-gating": {
            "__files": {
              "SKILL.md": {
                "path": "skills/core/bottleneck-gating/SKILL.md",
                "size": 2637,
                "ext": ".md"
              }
            }
          },
          "constraint-then-solve": {
            "__files": {
              "SKILL.md": {
                "path": "skills/core/constraint-then-solve/SKILL.md",
                "size": 2609,
                "ext": ".md"
              }
            }
          },
          "context-optimization": {
            "__files": {
              "SKILL.md": {
                "path": "skills/core/context-optimization/SKILL.md",
                "size": 2123,
                "ext": ".md"
              }
            }
          },
          "cron-troubleshoot": {
            "__files": {
              "references": {
                "__files": {
                  "details.md": {
                    "path": "skills/core/cron-troubleshoot/references/details.md",
                    "size": 2058,
                    "ext": ".md"
                  }
                }
              },
              "SKILL.md": {
                "path": "skills/core/cron-troubleshoot/SKILL.md",
                "size": 1996,
                "ext": ".md"
              }
            }
          },
          "e2e-test-strategy": {
            "__files": {
              "references": {
                "__files": {
                  "details.md": {
                    "path": "skills/core/e2e-test-strategy/references/details.md",
                    "size": 2014,
                    "ext": ".md"
                  }
                }
              },
              "SKILL.md": {
                "path": "skills/core/e2e-test-strategy/SKILL.md",
                "size": 2593,
                "ext": ".md"
              }
            }
          },
          "feedback-loop": {
            "__files": {
              "references": {
                "__files": {
                  "details.md": {
                    "path": "skills/core/feedback-loop/references/details.md",
                    "size": 1772,
                    "ext": ".md"
                  }
                }
              },
              "SKILL.md": {
                "path": "skills/core/feedback-loop/SKILL.md",
                "size": 1859,
                "ext": ".md"
              }
            }
          },
          "knowledge-extract": {
            "__files": {
              "references": {
                "__files": {
                  "details.md": {
                    "path": "skills/core/knowledge-extract/references/details.md",
                    "size": 1597,
                    "ext": ".md"
                  }
                }
              },
              "SKILL.md": {
                "path": "skills/core/knowledge-extract/SKILL.md",
                "size": 1830,
                "ext": ".md"
              }
            }
          },
          "landscape-first": {
            "__files": {
              "SKILL.md": {
                "path": "skills/core/landscape-first/SKILL.md",
                "size": 2701,
                "ext": ".md"
              }
            }
          },
          "measure-first": {
            "__files": {
              "SKILL.md": {
                "path": "skills/core/measure-first/SKILL.md",
                "size": 2775,
                "ext": ".md"
              }
            }
          },
          "plan-before-code": {
            "__files": {
              "SKILL.md": {
                "path": "skills/core/plan-before-code/SKILL.md",
                "size": 2720,
                "ext": ".md"
              }
            }
          },
          "plan-then-act": {
            "__files": {
              "SKILL.md": {
                "path": "skills/core/plan-then-act/SKILL.md",
                "size": 3076,
                "ext": ".md"
              }
            }
          },
          "prompt-discipline": {
            "__files": {
              "SKILL.md": {
                "path": "skills/core/prompt-discipline/SKILL.md",
                "size": 2387,
                "ext": ".md"
              }
            }
          },
          "pushback-when-wrong": {
            "__files": {
              "SKILL.md": {
                "path": "skills/core/pushback-when-wrong/SKILL.md",
                "size": 2942,
                "ext": ".md"
              }
            }
          },
          "quality-protocol": {
            "__files": {
              "references": {
                "__files": {
                  "details.md": {
                    "path": "skills/core/quality-protocol/references/details.md",
                    "size": 1031,
                    "ext": ".md"
                  }
                }
              },
              "SKILL.md": {
                "path": "skills/core/quality-protocol/SKILL.md",
                "size": 2564,
                "ext": ".md"
              }
            }
          },
          "re-verify-findings": {
            "__files": {
              "SKILL.md": {
                "path": "skills/core/re-verify-findings/SKILL.md",
                "size": 2637,
                "ext": ".md"
              }
            }
          },
          "read-before-build": {
            "__files": {
              "SKILL.md": {
                "path": "skills/core/read-before-build/SKILL.md",
                "size": 3185,
                "ext": ".md"
              }
            }
          },
          "session-closeout": {
            "__files": {
              "SKILL.md": {
                "path": "skills/core/session-closeout/SKILL.md",
                "size": 2458,
                "ext": ".md"
              }
            }
          },
          "session-distill": {
            "__files": {
              "references": {
                "__files": {
                  "details.md": {
                    "path": "skills/core/session-distill/references/details.md",
                    "size": 1347,
                    "ext": ".md"
                  }
                }
              },
              "SKILL.md": {
                "path": "skills/core/session-distill/SKILL.md",
                "size": 2416,
                "ext": ".md"
              }
            }
          },
          "show-your-work": {
            "__files": {
              "SKILL.md": {
                "path": "skills/core/show-your-work/SKILL.md",
                "size": 3029,
                "ext": ".md"
              }
            }
          },
          "verify-first": {
            "__files": {
              "SKILL.md": {
                "path": "skills/core/verify-first/SKILL.md",
                "size": 2287,
                "ext": ".md"
              }
            }
          },
          "workflow-decompose": {
            "__files": {
              "references": {
                "__files": {
                  "details.md": {
                    "path": "skills/core/workflow-decompose/references/details.md",
                    "size": 2186,
                    "ext": ".md"
                  }
                }
              },
              "SKILL.md": {
                "path": "skills/core/workflow-decompose/SKILL.md",
                "size": 2334,
                "ext": ".md"
              }
            }
          }
        }
      },
      "index.json": {
        "path": "skills/index.json",
        "size": 13869,
        "ext": ".json"
      },
      "optional": {
        "__files": {
          "chrome-devtools-mcp-bridge": {
            "__files": {
              "SKILL.md": {
                "path": "skills/optional/chrome-devtools-mcp-bridge/SKILL.md",
                "size": 3002,
                "ext": ".md"
              }
            }
          },
          "design-language": {
            "__files": {
              "SKILL.md": {
                "path": "skills/optional/design-language/SKILL.md",
                "size": 2771,
                "ext": ".md"
              }
            }
          },
          "funnel-pr-guard": {
            "__files": {
              "references": {
                "__files": {
                  "details.md": {
                    "path": "skills/optional/funnel-pr-guard/references/details.md",
                    "size": 539,
                    "ext": ".md"
                  }
                }
              },
              "SKILL.md": {
                "path": "skills/optional/funnel-pr-guard/SKILL.md",
                "size": 2438,
                "ext": ".md"
              }
            }
          },
          "persistent-memory": {
            "__files": {
              "SKILL.md": {
                "path": "skills/optional/persistent-memory/SKILL.md",
                "size": 2369,
                "ext": ".md"
              }
            }
          },
          "sql-migration-trio": {
            "__files": {
              "SKILL.md": {
                "path": "skills/optional/sql-migration-trio/SKILL.md",
                "size": 2280,
                "ext": ".md"
              }
            }
          },
          "token-compression": {
            "__files": {
              "SKILL.md": {
                "path": "skills/optional/token-compression/SKILL.md",
                "size": 1798,
                "ext": ".md"
              }
            }
          }
        }
      }
    }
  },
  "vercel.json": {
    "path": "vercel.json",
    "size": 441,
    "ext": ".json"
  },
  "web": {
    "__files": {
      "adapters-data.js": {
        "path": "web/adapters-data.js",
        "size": 1423,
        "ext": ".js"
      },
      "audit.html": {
        "path": "web/audit.html",
        "size": 7848,
        "ext": ".html"
      },
      "catalog.html": {
        "path": "web/catalog.html",
        "size": 6726,
        "ext": ".html"
      },
      "graph-data.js": {
        "path": "web/graph-data.js",
        "size": 91904,
        "ext": ".js"
      },
      "graph-stats.js": {
        "path": "web/graph-stats.js",
        "size": 1410,
        "ext": ".js"
      },
      "graph.html": {
        "path": "web/graph.html",
        "size": 9777,
        "ext": ".html"
      },
      "index.html": {
        "path": "web/index.html",
        "size": 25156,
        "ext": ".html"
      },
      "install-data.js": {
        "path": "web/install-data.js",
        "size": 794,
        "ext": ".js"
      },
      "site-data.js": {
        "path": "web/site-data.js",
        "size": 101873,
        "ext": ".js"
      },
      "skill-deps.js": {
        "path": "web/skill-deps.js",
        "size": 1541,
        "ext": ".js"
      },
      "styles.css": {
        "path": "web/styles.css",
        "size": 18769,
        "ext": ".css"
      },
      "why.html": {
        "path": "web/why.html",
        "size": 5516,
        "ext": ".html"
      }
    }
  },
  "workflows": {
    "__files": {
      "ci-cd-vercel.md": {
        "path": "workflows/ci-cd-vercel.md",
        "size": 2688,
        "ext": ".md"
      },
      "e2e-on-pr.md": {
        "path": "workflows/e2e-on-pr.md",
        "size": 3212,
        "ext": ".md"
      },
      "release-train.md": {
        "path": "workflows/release-train.md",
        "size": 2822,
        "ext": ".md"
      },
      "session-to-skill.md": {
        "path": "workflows/session-to-skill.md",
        "size": 3426,
        "ext": ".md"
      }
    }
  }
};
