// Skill dependency map (cross-references between skills in their bodies).
// Generated by scripts/gen-site-data.py.

const SKILL_DEPS = {
  "anti-slop": [],
  "api-design": [],
  "automation-pick": [],
  "bottleneck-gating": [
    "measure-first",
    "verify-first"
  ],
  "constraint-then-solve": [],
  "context-optimization": [],
  "cron-troubleshoot": [],
  "e2e-test-strategy": [],
  "feedback-loop": [],
  "knowledge-extract": [],
  "landscape-first": [
    "bottleneck-gating",
    "measure-first",
    "pushback-when-wrong"
  ],
  "measure-first": [
    "bottleneck-gating",
    "pushback-when-wrong",
    "verify-first"
  ],
  "plan-before-code": [],
  "plan-then-act": [],
  "prompt-discipline": [],
  "pushback-when-wrong": [
    "measure-first",
    "show-your-work",
    "verify-first"
  ],
  "quality-protocol": [],
  "re-verify-findings": [
    "pushback-when-wrong",
    "verify-first"
  ],
  "read-before-build": [
    "plan-then-act",
    "re-verify-findings",
    "verify-first"
  ],
  "session-closeout": [],
  "session-distill": [
    "knowledge-extract"
  ],
  "show-your-work": [
    "bottleneck-gating",
    "pushback-when-wrong",
    "verify-first"
  ],
  "verify-first": [
    "measure-first",
    "re-verify-findings",
    "read-before-build"
  ],
  "workflow-decompose": [],
  "chrome-devtools-mcp-bridge": [],
  "design-language": [],
  "funnel-pr-guard": [],
  "persistent-memory": [],
  "sql-migration-trio": [],
  "token-compression": []
};
